import type { Metadata } from "next";
import { cn } from '@/lib/utils'
import { DM_Serif_Display } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "@/components/Providers";

const dm_serif = DM_Serif_Display({ subsets: ["latin"], style: ["normal"], weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='h-full'>
      <body 
        className={cn(
          "relative h-full font-sans antialiased", 
          dm_serif.className
        )}>
          <main className='relative flex flex-col min-h-screen'>
            <Providers>
            <NavBar/>
            <div className='flex-grow flex-1 min-h-screen'>  
              {children}
            </div>
            <Footer/>
            </Providers>
          </main>
      </body>
    </html>
  )
}
